In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
from Week2_Q2_Template import mr
plt.style.use('ggplot')


In [2]:
df = pd.read_csv('prob2data.csv')
price = df['price']
clrdf = df[['bedrooms', 'bathrooms', 'sqft_living', 'floors', 'yr_built']]
print(clrdf.mean())
clrdf = (clrdf-clrdf.mean())/clrdf.std()
clrdf = clrdf.to_numpy()
price = price.to_numpy()
print(clrdf)
print(price)

bedrooms          3.370842
bathrooms         2.114757
sqft_living    2079.899736
floors            1.494309
yr_built       1971.005136
dtype: float64
[[-0.39872792 -1.44743008 -0.97981235 -0.91540583 -0.54488517]
 [-0.39872792  0.17560263  0.53362199  0.93648411 -0.68106275]
 [-1.47392526 -1.44743008 -1.42622105 -0.91540583 -1.29386186]
 ...
 [-1.47392526 -1.77203663 -1.15402062  0.93648411  1.29351217]
 [-0.39872792  0.50020918 -0.52251564  0.93648411  1.12329019]
 [-1.47392526 -1.77203663 -1.15402062  0.93648411  1.25946777]]
[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [3]:
iters = 5000
mr_o = mr()
w = np.multiply(1000,np.random.rand(6))
a = mr_o.bgdMulti(clrdf.T,price.T,w,0.5,iters)
b = mr_o.bgdMulti(clrdf.T,price.T,w,0.1,iters)
c = mr_o.bgdMulti(clrdf.T,price.T,w,0.01,iters)
d = mr_o.bgdMulti(clrdf.T,price.T,w,0.05,iters)

x_ar = [i for i in range(iters)]
y_ar_a = a[1]
y_ar_b = b[1]
y_ar_c = c[1]
y_ar_d = d[1]

plt.plot(x_ar,y_ar_a,label="α = 0.5")
plt.plot(x_ar,y_ar_b,label="α = 0.1")
plt.plot(x_ar,y_ar_c,label="α = 0.01")
plt.plot(x_ar,y_ar_d,label="α = 0.05")
plt.title("Variaton of J with alpha")
plt.xlabel('No of iterations')
plt.ylabel('J')  
plt.legend()
plt.savefig('J_2.png',dpi=500)
plt.show()

ValueError: shapes (6,) and (21613,5) not aligned: 6 (dim 0) != 21613 (dim 0)

In [20]:
al = np.array([540182.15879331, -62570.63794173,  52863.96758866, 275061.94892609, 30185.44439133, -99525.84920572])
bl = np.array([1, -0.39872792, -1.44743008, -0.97981235, -0.91540583, -0.54488517])

np.dot(al,bl)

245703.05519095418

In [28]:
ar = np.array([4,2.5,2570,2,2005])

In [30]:
df = pd.read_csv('prob2data.csv')
price = df['price']
clrdf = df[['bedrooms', 'bathrooms', 'sqft_living', 'floors', 'yr_built']]

In [34]:
t = (ar - clrdf.mean())/clrdf.std()

In [45]:
alp = np.array([1,0.67646941, 0.50020918, 0.53362199, 0.93648411, 1.15733459])
np.dot(alp,al)

584160.6638406984